// Copyright 2021-2022 zcloak authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @zcloak/dev

export const packageInfo = { name: '@zcloak/keyring', path: 'auto', type: 'auto', version: '0.0.1-8-x.0-x.0' };
